#! /bin/sh
#
# jump.sh
# Copyright (C) 2018 stcarolas <stcarolas@carbon>
#
# Distributed under terms of the MIT license.
#


ls --group-directories-first | m1
local target=$(cat /tmp/m1)
if [ -n "$target" ]; then
  cd $target
fi
