#! /bin/sh
#
# jump.sh
# Copyright (C) 2018 stcarolas <stcarolas@carbon>
#
# Distributed under terms of the MIT license.
#


ls --group-directories-first ~/Coding/projects | m1
export target=~/Coding/projects/$(cat /tmp/m1)
if [ -d "$target" ]; then
  cd $target
else
  rifle $target
fi
